RUBROS_MAPPING = {
    'ingresos_estaciones':            'A - INGRESOS',
    'costoventa_estaciones':          'B - COSTO DE VENTA',
    'gastos_operacion_estaciones':    'E - GASTOS DE OPERACION',
    'nomina_estaciones':              'C - NOMINA',
    'costo_social_estaciones':        'D - COSTO SOCIAL',
    'mantenimiento_estaciones':       'F - MANTENIMIENTO',
    'gastos_fijos_estaciones':        'H - GASTOS FIJOS',
    'margen_estaciones':              'MARGEN DE UTILIDAD',
}
RUBROS_STAFF_MAPPING = {
    'gastos_operacion_staff':    'E - GASTOS DE OPERACION',
    'nomina_staff':              'C - NOMINA',
    'costo_social_staff':        'D - COSTO SOCIAL',
    'mantenimiento_staff':       'F - MANTENIMIENTO',
    'gastos_fijos_staff':        'H - GASTOS FIJOS',
}

CONCEPTOS_GASTOS_FIJOS ={
    'AGUA SERVICIO': ['AGUA SERVICIO'],
    'ARRENDAMIENTO A PERSONAS FISICAS RESID NAL': ['ARRENDAMIENTO A PERSONAS FISICAS RESID NAL'],
    'ARRENDAMIENTO EXTRANJEROS': ['ARRENDAMIENTO EXTRANJEROS'],
    'ARRENDAMIENTO VEHICULOS': ['ARRENDAMIENTO VEHICULOS'],
    'ENERGIA ELECTRICA': [
        'ENERGIA ELECTRICA',
        'ENERGÍA ELÉCTRICA'
        ],
    'TELEFONO, INTERNET': ['TELEFONO, INTERNET'],
    'ARRENDAMIENTO A PERSONAS MORALES RESID NAL': [
        'ARRENDAMIENTO',
        'ARRENDAMIENTO PM',
        'ARRENDAMIENTO EXTRANJEROS',
        'ARRENDAMIENTO A PERSONAS FISICAS RESID NAL',
        'ARRENDAMIENTO A PERSONAS MORALES RESID NAL'
    ],
    'ARRENDAMIENTO A PERSONAS MORALES RESID NAL': ['ARRENDAMIENTO A PERSONAS MORALES RESID NAL','Arrendamiento','Arrendamiento a personas morales resid nal','Arrendamiento Tecnologico '],
}
CONCEPTOS_MANTENIMIENTO = {
    'ACCESORIOS': ['ACCESORIOS'],
    'ANALISIS DE LA CALIDAD DE COMBUSTIBLE NOM-016-CRE-2016': ['ANALISIS DE LA CALIDAD DE COMBUSTIBLE NOM-016-CRE-2016'],
    'BASURA Y RECOLECCIÓN': ['BASURA Y RECOLECCIÓN'],
    'CALCAMONIAS Y SEÑALAMIENTOS': ['CALCAMONIAS Y SEÑALAMIENTOS'],
    'CALIBRACIONES': ['CALIBRACIONES'],
    'CEDULA DE OPERACIÓN ANUAL (COA)': ['CEDULA DE OPERACIÓN ANUAL (COA)'],
    'CERTIFICACION ASEA': ['CERTIFICACION ASEA'],
    'CERTIFICACION SASISOPA': ['CERTIFICACION SASISOPA'],
    'DICTAMEN DE CALIDAD DE LOS PETROLIFEROS NOM-016-CRE-2016': ['DICTAMEN DE CALIDAD DE LOS PETROLIFEROS NOM-016-CRE-2016'],
    'DICTAMEN DE OPERACIÓN Y MANTENIMIENTO NOM-005-ASEA-2026': ['DICTAMEN DE OPERACIÓN Y MANTENIMIENTO NOM-005-ASEA-2026'],
    'DICTAMEN INSTALACION ELECTRICAS NOM-001-SEDE-2012': ['DICTAMEN INSTALACION ELECTRICAS NOM-001-SEDE-2012'],
    'EXTINTORES': ['EXTINTORES'],
    'FUMIGACIÓN': ['FUMIGACIÓN'],
    'GASTOS ASEA': ['GASTOS ASEA'],
    'GASTOS CRE': ['GASTOS CRE'],
    'HERRAMIENTAS DE TRABAJO': ['HERRAMIENTAS DE TRABAJO'],
    'JARDINERÍA': ['JARDINERÍA'],
    'LIMPIEZA ECOLOGICA': ['LIMPIEZA ECOLOGICA'],
    'LIMPIEZA FALDON, TOTEM, BAÑOS': ['LIMPIEZA FALDON, TOTEM, BAÑOS'],
    'MANTENIMIENTO A LOS TANQUES': ['MANTENIMIENTO A LOS TANQUES'],
    'MANTENIMIENTO DE EDIFICIOS': ['MANTENIMIENTO DE EDIFICIOS'],
    'MANTENIMIENTO DE EQUIPO DE COMPUTO': ['MANTENIMIENTO DE EQUIPO DE COMPUTO'],
    'MANTENIMIENTO DE ESTACIONES': ['MANTENIMIENTO DE ESTACIONES'],
    'MANTENIMIENTO DE VEHICULOS': ['MANTENIMIENTO DE VEHICULOS'],
    'MANTENIMIENTO ELECTRICO': ['MANTENIMIENTO ELECTRICO'],
    'MANTENIMIENTO EQUIPO DE ESTACION': ['MANTENIMIENTO EQUIPO DE ESTACION'],
    'MANTENIMIENTO GENERAL': ['MANTENIMIENTO GENERAL'],
    'PINTURAS Y ACABADOS': ['PINTURAS Y ACABADOS'],
    'PLOMERIA Y FERRETERIA': ['PLOMERIA Y FERRETERIA'],
    'PROTECCIÓN CÍVIL, BOMBEROS Y MUNICIPALES': ['PROTECCIÓN CÍVIL, BOMBEROS Y MUNICIPALES'],
    'PRUEBAS HERMETICIDAD': ['PRUEBAS HERMETICIDAD'],
    'RECOLECCIÓN DE RESIDUOS': ['RECOLECCIÓN DE RESIDUOS'],
    'REFACCIONES DISPENSARIOS': ['REFACCIONES DISPENSARIOS'],
    'SEGURIDAD E HIGIENE AMBIENTAL': ['SEGURIDAD E HIGIENE AMBIENTAL'],
    'VERIFICACIÓN ELÉCTRICA': ['VERIFICACIÓN ELÉCTRICA'],
    'VERIFICACIONES DE ESTACIONES': ['VERIFICACIONES DE ESTACIONES'],
    'VERIFICACIONES PROFECO': ['VERIFICACIONES PROFECO']
}
CONCEPTOS_COSTO_SOCIAL={
    'APORTACIONES AL INFONAVIT': ['APORTACIONES AL INFONAVIT'],
    'APORTACIONES AL SAR': ['APORTACIONES AL SAR'],
    'CUOTAS AL IMSS': ['CUOTAS AL IMSS'],
    'IMPUESTO ESTATAL SOBRE NÓMINAS': ['IMPUESTO ESTATAL SOBRE NÓMINAS']
}

CONCEPTOS_NOMINA={
    'AGUINALDO': ['AGUINALDO'],
    'COMPENSACIONES': ['COMPENSACIONES'],
    'DIAS FESTIVOS': ['DIAS FESTIVOS'],
    'FONDO DE AHORRO': ['FONDO DE AHORRO'],
    'INDENMIZACIONES': ['INDENMIZACIONES'],
    'PREMIOS DE ASISTENCIA': ['PREMIOS DE ASISTENCIA'],
    'PREMIOS DE PUNTUALIDAD': ['PREMIOS DE PUNTUALIDAD'],
    'PREVISION SOCIAL': ['PREVISION SOCIAL'],
    'PRIMA DOMINICAL': ['PRIMA DOMINICAL'],
    'PRIMA VACACIONAL': ['PRIMA VACACIONAL'],
    'PRIMAS DE ANTIGUEDAD': ['PRIMAS DE ANTIGUEDAD'],
    'PTU': ['PTU'],
    'SUELDOS Y SALARIOS': ['SUELDOS Y SALARIOS'],
    'TIEMPOS EXTRAS': ['TIEMPOS EXTRAS'],
    'VACACIONES': ['VACACIONES'],
}
CONCEPTOS_GASTOS_OPERACION = {
    'AGUA PARA CONSUMO': ['AGUA PARA CONSUMO','AGUA CONSUMO','AGUA DE CONSUMO'],
    'ASESORIA ACEHICO': ['ASESORIA ACEHICO'],
    'ASESORÍA EN SISTEMAS': ['ASESORÍA EN SISTEMAS'],
    'ASISTENCIA TÉCNICA': ['ASISTENCIA TÉCNICA'],
    'CALCOMANIAS Y SEÑALAMIENTOS': ['CALCOMANIAS Y SEÑALAMIENTOS'],
    'CAPACITACIÓN AL PERSONAL': ['CAPACITACIÓN AL PERSONAL'],
    'CONSUMOS PROPIOS COMBUSTIBLES': ['CONSUMOS PROPIOS COMBUSTIBLES'],
    'CONTINGENCIA COVID': ['CONTINGENCIA COVID'],
    'CONTRATACION EMPLEADOS': ['CONTRATACION EMPLEADOS'],
    'CUMPLIMIENTO SAT ANEXO 30 Y 31': ['CUMPLIMIENTO SAT ANEXO 30 Y 31'],
    'COMBUSTIBLES REEMBOLSOS': ['COMBUSTIBLES REEMBOLSOS'],
    'CUOTAS Y SUSCRIPCIONES': ['CUOTAS Y SUSCRIPCIONES'],
    'EVENTOS': ['EVENTOS'],
    'FALTANTES': ['FALTANTES'],
    'FLETES COMBUSTIBLE': ['FLETES COMBUSTIBLE'],
    'FLETES MENSAJERIA': ['FLETES MENSAJERIA'],
    'GAS NATURAL': ['GAS NATURAL'],
    'GASTOS NO DEDUCIBLES (SIN REQUISITOS FISCALES)': ['GASTOS NO DEDUCIBLES (SIN REQUISITOS FISCALES)'],
    'HONORARIOS ADMINISTRATIVOS P.F.': ['HONORARIOS ADMINISTRATIVOS P.F.'],
    'HONORARIOS ADMINISTRATIVOS P.M.': ['HONORARIOS ADMINISTRATIVOS P.M.'],
    'HONORARIOS DE CONSULTORIA': ['HONORARIOS DE CONSULTORIA'],
    'HONORARIOS FISCALES P.F.': ['HONORARIOS FISCALES P.F.'],
    'HONORARIOS FISCALES P.M.': ['HONORARIOS FISCALES P.M.'],
    'HONORARIOS LEGALES P.F.': ['HONORARIOS LEGALES P.F.'],
    'HONORARIOS LEGALES P.M.': ['HONORARIOS LEGALES P.M.'],
    'LICENCIAS Y PERMISOS': ['LICENCIAS Y PERMISOS'],
    'LICENCIAS, SOFTWARE, ANTIVIRUS': ['LICENCIAS, SOFTWARE, ANTIVIRUS'],
    'LIMPIEZA': ['LIMPIEZA'],
    'MULTAS Y RECARGOS': ['MULTAS Y RECARGOS'],
    'OTROS GASTOS': ['OTROS GASTOS'],
    'OTROS IMPUESTOS Y DERECHOS': ['OTROS IMPUESTOS Y DERECHOS'],
    'PAPELERÍA Y ARTÍCULOS DE OFICINA': ['PAPELERÍA Y ARTÍCULOS DE OFICINA'],
    'PREDIALES': ['PREDIALES'],
    'PROPAGANDA Y PUBLICIDAD': ['PROPAGANDA Y PUBLICIDAD'],
    'RECOLECCION DE BASURA': ['RECOLECCION DE BASURA'],
    'RENTAS NO DEDUCIBLES': ['RENTAS NO DEDUCIBLES'],
    'RENTA EQUIPO DE SISTEMAS': ['RENTA EQUIPO DE SISTEMAS'],
    'SEGUROS Y FIANZAS': ['SEGUROS Y FIANZAS'],
    'SERVICIOS ADMINISTRATIVOS': ['SERVICIOS ADMINISTRATIVOS'],
    'TIMBRADO FACTURAS': ['TIMBRADO FACTURAS'],
    'TRASLADO DE VALORES': ['TRASLADO DE VALORES'],
    'UNIFORMES': ['UNIFORMES'],
    'VIÁTICOS Y GASTOS DE VIAJE': ['VIÁTICOS Y GASTOS DE VIAJE'],
    'VIGILANCIA Y SEGURIDAD': ['VIGILANCIA Y SEGURIDAD'],
}

CONCEPTOS_INGRESOS = {
    'MAXIMA': [
        'INGRESOS MAGNA',
        'INGRESOS FORANEOS MAGNA',
        'INGRESOS GASOLINA REGULAR',
        'INGRESOS MAXIMA',
        'INGRESOS MAXIMA 8%',
        'INGRESOS FORANEOS MAXIMA',
        'SOBRANTE REGULAR',
        'SOBRANTE MAGNA',
    ],
    'DIESEL': [
        'INGRESOS DIESEL',
        'INGRESOS FORANEOS DIESEL',
        'SOBRANTE DIESEL',
    ],
    'SUPER': [
        'INGRESOS PREMIUM',
        'INGRESOS GASOLINA PREMIUM',
        'INGRESOS FORANEOS PREMIUM',
        'SOBRANTE PREMIUM',
    ],
    'PREPAGO facturación': [
        'INGRESOS POR ANTICIPOS',
        'VENTAS Y/O SERV GRAV A TASA GRAL NAL PTE RELAC',
        'DEV, DESCUENTOS O BONIF SOBRE INGRESOS',
        'OTROS INGRESOS PROPIOS',
        'OTROS INGRESOS'
    ],
    'INGRESOS ACEITES Y LUBRICANTES': [
        'INGRESOS ADITIVOS',
        'INGRESOS ESPECIALES',
        'INGRESOS FORANEOS ADITIVOS',
        'INGRESOS FORANEOS ESPECIALES',
        'INGRESOS FORANEOS LUBRICANTES',
        'INGRESOS ACEITES',
        'INGRESOS LUBRICANTES',
        'INGRESOS ACEITES Y LUBRICANTES'
    ],
    'SOBRANTE REGULAR': [
        'SOBRANTE MAGNA',
        'SOBRANTE REGULAR',
        'SOBRANTES'
    ],
    'SOBRANTE PREMIUM': [
        'SOBRANTE PREMIUM',
    ],
    'SOBRANTE DIESEL': [
        'SOBRANTE DIESEL',
    ],

}

CONCEPTOS_COSTOVENTA={
    'GASOLINA REGULAR':[
        'COSTO FORANEO MAGNA',
        'COSTO MAXIMA',
        'COSTO MAGNA'
    ],
    'GASOLINA PREMIUM': [
        'COSTO PREMIUM',
        'COSTO FORANEO PREMIUM',
        'COSTO PREMIUM',
        'COSTO SUPER'
    ],
    'DIESEL': [
        'COSTO DIESEL',
        'COSTO FORANEO DIESEL',
    ],
    'MERMA GASOLINA REGULAR': [
       'Merma Magna',
       'MERMA MAXIMA'

    ],
    'MERMA GASOLINA PREMIUM': [
       'Merma Premium',
       'MERMA SUPER'
    ],
    'MERMA DIESEL':[
         'Merma Diesel'
    ],
    'ADITIVO TOTAL POWER GASOLINA REG':[
        'ADITIVO PARA GASOLINA TMAXIMA( REGULAR)',
        'ADITIVO TOTAL POWER MAGNA',
        'COSTO ADITIVO TOTAL POWER',
        'Aditivo magna',
        'COSTO ADITIVOS'

    ],
    'ADITIVO TOTAL POWER GASOLINA PREM':[
       'ADITIVO PARA GASOLINA TSUPER (PREMIUM)',
       'ADITIVO TOTAL POWER PREMIUM',
       'COSTO ADITIVO SUPER',
       'Aditivo Total Premium',
       'Aditivo Total Power Super'
    ],
    'FLETE GASOLINA REGULAR':[
        'FLETE MAGNA'
    ],
    'FLETE GASOLINA PREMIUM':[
        'FLETE PREMIUM'
    ],
    'FLETE DIESEL':[
        'FLETE DIESEL'
    ],
    'ESTIMULO REGULAR':[
        'ESTIMULO IEPS MAXIMA',
        'Estimulo IEPS Magna'
    ],
    'ESTIMULO PREMIUM':[
        'ESTIMULO IEPS SUPER',
        'Estimulo IEPS Premium'
    ],
    'DESCUENTO SOBRE VENTA':[
        'Dev, descuentos o bonif sobre ingresos',
        'Dev. Desctos, bonificaciones a clientes',
        'DESCUENTO SOBRE VENTAS',
        'DEV DESCTOS O BONIFICACIONES S/VENTAS',
        'Dev, desctos o bonifi s vtas y/o serv tasa gral',
        'Devoluciones por promociones mkt',
        'DESCUENTO SOBRE VENTA'
    ],
    'COSTO UNIFORMES':[
        'Gasto por venta de uniformes'
    ],
    'COSTO ACEITES Y LUBRICANTES':[
        'COSTO ADITIVOS'
        'COSTO ESPECIALES'
        'COSTO FORANEO ADITIVOS'
        'COSTO ACEITES'
        'COSTO FORANEO LUBRICANTES',
        'COSTO LUBRICANTES',
        'COSTO FORANEO ESPECIALES',
        'DESCUENTO SOBRE VENTA'
    ]
}
CONCEPTOS_MARGEN_UTILIDAD = {
    'REGULAR': {
        'ingresos': [
            'MAXIMA',
            'SOBRANTE REGULAR'
        ],
        'costo_venta': [
            'GASOLINA REGULAR',
            'MERMA GASOLINA REGULAR',
            'ADITIVO TOTAL POWER GASOLINA REG',
            'FLETE GASOLINA REGULAR',
            'ESTIMULO REGULAR'
        ]
    },
    'PREMIUM': {
        'ingresos': ['SUPER', 'SOBRANTE PREMIUM'],
        'costo_venta': ['GASOLINA PREMIUM', 'MERMA GASOLINA PREMIUM', 'ADITIVO TOTAL POWER GASOLINA PREMIUM', 'FLETE GASOLINA PREMIUM', 'ESTIMULO PREMIUM']
    },
    'DIESEL': {
        'ingresos': ['DIESEL', 'SOBRANTE DIESEL'],
        'costo_venta': ['DIESEL', 'MERMA DIESEL', 'FLETE DIESEL']
    },
    'OTROS CONCEPTOS': {
        'ingresos': ['PREPAGO FACTURACIÓN'],
        'costo_venta': ['DESCUENTO SOBRE VENTA', 'COSTO UNIFORMES']
    },
    'ACEITES Y LUBRICANTES': {
        'ingresos': ['INGRESOS ACEITES Y LUBRICANTES'],
        'costo_venta': ['COSTO ACEITES Y LUBRICANTES']
    },
}
